### PR TITLE
Generate more idiomatic code for Rust

### PR DESCRIPTION
**Pull request by utensil**
The last version of Rust generator has one major performance issue, it derived the `Copy` trait for the GA struct and use pass-by-value in operator overloading and other methods, it's not idiomatic and will be very inefficient for high dimensions.

This PR solves this issue by implementing all combination of value/reference parameter of the unary operators (4 of them in total: val val, val ref, ref val, ref ref), the result is:

If I need to do `a + b * c`, `b` and `c` needs to be ref (it's still inconvenient but Rust demands to take reference explicitly, but the return value of `b * c` can use the val version of `+` which will take the reference in the method body so it's still efficient. (I should comment the code instead of explaining with empty words.)

The implementation of this is tedious, so it is facilitated by two macros inspired by and simplified from the macro in `rustsim/nalgebra`: see https://github.com/rustsim/nalgebra/blob/master/src/geometry/transform_ops.rs#L108 for example usage and they're defined in https://github.com/rustsim/nalgebra/blob/master/src/geometry/op_macros.rs .

The PR is now working but still a work-in-progress.

### CODE REVIEW

**Comment by utensil** [comment]
I'll also try to fix the `make GEN_LANG="rust" r600` issue in this PR:

```
$ make GEN_LANG="rust" r600
CUSTOM METRIC :  6 0 0
[R600] Generated rust
error[E0277]: the trait bound `[f64; 64]: std::default::Default` is not satisfied
  --> rust/r600.rs:23:5
   |
23 |     mvec: [float_t; basis_count]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::default::Default` is not implemented for `[f64; 64]`
   |
   = help: the following implementations were found:
             <&[T] as std::default::Default>
             <&mut [T] as std::default::Default>
             <[T; 0] as std::default::Default>
             <[T; 10] as std::default::Default>
           and 31 others
   = note: required by `std::default::Default::default`

error[E0277]: `[f64; 64]` doesn't implement `std::fmt::Debug`
  --> rust/r600.rs:23:5
   |
23 |     mvec: [float_t; basis_count]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `[f64; 64]` cannot be formatted using `{:?}` because it doesn't implement `std::fmt::Debug`
   |
   = help: the trait `std::fmt::Debug` is not implemented for `[f64; 64]`
   = note: required because of the requirements on the impl of `std::fmt::Debug` for `&[f64; 64]`
   = note: required for the cast to the object type `dyn std::fmt::Debug`

error[E0369]: binary operation `==` cannot be applied to type `[f64; 64]`
  --> rust/r600.rs:23:5
   |
23 |     mvec: [float_t; basis_count]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: an implementation of `std::cmp::PartialEq` might be missing for `[f64; 64]`

error[E0369]: binary operation `!=` cannot be applied to type `[f64; 64]`
  --> rust/r600.rs:23:5
   |
23 |     mvec: [float_t; basis_count]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: an implementation of `std::cmp::PartialEq` might be missing for `[f64; 64]`

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0277, E0369.
For more information about an error, try `rustc --explain E0277`.
```

**Comment by utensil** [comment]
@enkimute This PR is now finished and ready for review. :smile_cat:

**Comment by enkimute** [comment]
```bash
/bin/bash: -c: line 0: conditional binary operator expected
/bin/bash: -c: line 0: syntax error near `cpp'
/bin/bash: -c: line 0: `if [[ ""csharp cpp python rust"" == *"cpp"* ]]; then g++ -o cpp/c_cpp cpp/c.cpp -std=c++11; ./cpp/c_cpp >> out1; fi'
makefile:12: recipe for target 'c' failed
make: *** [c] Error 1
```
hmm makefile still acting up .. (on another machine, WSL, ubuntu)

**Comment by enkimute** [comment]
with single quotes it works here ..

**Pull request merged**
